[ALLUXIO-1909] Fix comments and now we bootstrap to create alluxio-env.sh

diff --git a/bin/alluxio b/bin/alluxio
--- a/bin/alluxio
+++ b/bin/alluxio
@@ -46,61 +46,64 @@ function bootstrapConf {
     echo ${usage}
     exit 1
   fi
+  local master=${1}
   local ufs=${2:-local}
 
   ALLUXIO_CONF_DIR="${BIN}/../conf"
-  local dst="${ALLUXIO_CONF_DIR}/alluxio-site.properties"
+  local src="${ALLUXIO_CONF_DIR}/alluxio-env.sh.template"
+  local dst="${ALLUXIO_CONF_DIR}/alluxio-env.sh"
+
   if [[ -e ${dst} ]]; then
     echo "${dst} already exists"
     return
   fi
 
+  if [[ ! -e ${src} ]]; then
+    echo "Cannot find ${src}"
+    exit 1
+  fi
+
   if [[ $(uname -s) == Darwin ]]; then
     # Assuming Mac OS X
     TOTAL_MEM=$(sysctl hw.memsize | cut -d ' ' -f2)
-    TOTAL_MEM=$[TOTAL_MEM / 1024]
+    TOTAL_MEM=$[TOTAL_MEM / 1024 / 1024]
     TOTAL_MEM=$[TOTAL_MEM * 2 / 3]
     RAMDISK_FOLDER="/Volumes/ramdisk"
   else
     # Assuming Linux
     TOTAL_MEM=$(awk '/MemTotal/{print $2}' /proc/meminfo)
-    TOTAL_MEM=$[TOTAL_MEM * 2 / 3]
+    TOTAL_MEM=$[TOTAL_MEM / 1024 * 2 / 3]
     RAMDISK_FOLDER="/mnt/ramdisk"
   fi
 
-  echo "# This file is initially created by $0" >> ${dst}
-  echo "# Users can override, delete or add more configuration options." >> ${dst}
-  echo "# A complete list of supported options can be found at http://alluxio.org/documentation/" >> ${dst}
-  echo "" >> ${dst}
-
   # Set the master hostname
-  echo "alluxio.master.address=$1" >> ${dst}
+  ALLUXIO_MASTER_ADDRESS=${master}
 
   # Set the worker memory size
-  echo "alluxio.worker.memory.size=${TOTAL_MEM}KB" >> ${dst}
+  ALLUXIO_WORKER_MEMORY_SIZE="${TOTAL_MEM}MB"
 
   # Set the ramdisk folder
-  echo "alluxio.worker.tieredstore.level0.dirs.path=${RAMDISK_FOLDER}" >> ${dst}
+  ALLUXIO_RAM_FOLDER="${RAMDISK_FOLDER}"
 
   # Set under storage specific configuration
   case ${ufs} in
     local)
-      echo "alluxio.underfs.address=${ALLUXIO_HOME}/underFSStorage/" >> ${dst}
+      ALLUXIO_UNDERFS_ADDRESS="\${ALLUXIO_HOME}/underFSStorage/"
       ;;
     hdfs)
-      echo "alluxio.underfs.address=hdfs://localhost:9000/alluxio/" >> ${dst}
+      ALLUXIO_UNDERFS_ADDRESS="hdfs://localhost:9000/alluxio/"
       ;;
     s3)
-      echo "alluxio.underfs.address=s3n://bucket/directory/" >> ${dst}
+      ALLUXIO_UNDERFS_ADDRESS="s3n://bucket/directory/"
       ;;
     gcs)
-      echo "alluxio.underfs.address=gs://bucket/directory/" >> ${dst}
+      ALLUXIO_UNDERFS_ADDRESS="gs://bucket/directory/"
       ;;
     glusterfs)
-      echo "alluxio.underfs.address=/gluster_vol/" >> ${dst}
+      ALLUXIO_UNDERFS_ADDRESS="/gluster_vol/"
       ;;
     swift)
-      echo "alluxio.underfs.address=swift://swift-container/" >> ${dst}
+      ALLUXIO_UNDERFS_ADDRESS="swift://swift-container/"
       ;;
     *)
       rm ${dst}
@@ -108,6 +111,27 @@ function bootstrapConf {
       exit 1
       ;;
   esac
+
+  cat ${src} | while read -r line
+  do
+    case ${line} in
+      "# ALLUXIO_MASTER_ADDRESS")
+        echo "ALLUXIO_MASTER_ADDRESS=${ALLUXIO_MASTER_ADDRESS}" >> ${dst}
+        ;;
+      "# ALLUXIO_WORKER_MEMORY_SIZE")
+        echo "ALLUXIO_WORKER_MEMORY_SIZE=${ALLUXIO_WORKER_MEMORY_SIZE}" >> ${dst}
+        ;;
+      "# ALLUXIO_RAM_FOLDER")
+        echo "ALLUXIO_RAM_FOLDER=${ALLUXIO_RAM_FOLDER}" >> ${dst}
+        ;;
+      "# ALLUXIO_UNDERFS_ADDRESS")
+        echo "ALLUXIO_UNDERFS_ADDRESS=${ALLUXIO_UNDERFS_ADDRESS}" >> ${dst}
+        ;;
+      *)
+        echo ${line} >> ${dst}
+    esac
+  done
+  echo "${dst} is created."
 }
 
 # bootstrap creates alluxio-env.sh
