[ALLUXIO1-1910] Add main function to bin/alluxio

diff --git a/bin/alluxio b/bin/alluxio
--- a/bin/alluxio
+++ b/bin/alluxio
@@ -1,12 +1,5 @@
 #!/usr/bin/env bash
 
-LAUNCHER=
-# If debugging is enabled propagate that through to sub-shells
-if [[ $- == *x* ]]; then
-  LAUNCHER="bash -x"
-fi
-BIN=$(cd "$( dirname "$0" )"; pwd)
-
 function printUsage {
   echo "Usage: alluxio COMMAND [GENERIC_COMMAND_OPTIONS] [COMMAND_ARGS]"
   echo
@@ -34,16 +27,9 @@ function printUsage {
   echo "GENERIC_COMMAND_OPTIONS supports:"
   echo -e "  -D<property=value>\t Use a value for a given Alluxio property"
   echo
+  # TODO(binfan): Fix help function for alluxio script
   echo "Commands print help when invoked without parameters."
 }
-
-if [[ $# == 0 ]]; then
-  printUsage
-  exit 1
-fi
-
-COMMAND=$1
-shift
 
 function bootstrapConf {
   local usage="Usage: $0 bootstrap-conf <alluxio_master_hostname> [local|hdfs|s3|gcs|glusterfs|swift]"
@@ -125,16 +111,6 @@ EOF
   echo "${dst} is created."
 }
 
-# bootstrap creates alluxio-env.sh
-if [[ "${COMMAND}" == "bootstrap-conf" ]]; then
-  bootstrapConf "$@"
-  exit 0
-fi
-
-DEFAULT_LIBEXEC_DIR="${BIN}"/../libexec
-ALLUXIO_LIBEXEC_DIR=${ALLUXIO_LIBEXEC_DIR:-$DEFAULT_LIBEXEC_DIR}
-. ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
-
 function killAll {
   if [[ $# -ne 1 ]]; then
     echo "Usage: alluxio killAll <WORD>"
@@ -184,133 +160,162 @@ function copyDir {
   wait
 }
 
-PARAMETER=""
-ALLUXIO_SHELL_JAVA_OPTS=""
-
-case ${COMMAND} in
-"format")
-  if [[ $# -eq 1 ]]; then
-    if [[ $1 == "-s" ]]; then
-      if [[ -e ${ALLUXIO_UNDERFS_ADDRESS} ]]; then
-        # if ufs is local filesystem and already exists
-        exit 0
-      else
-        declare -a schemes=(hdfs s3 s3n glusterfs swift oss gcs)
-        for scheme in ${schemes[@]}; do
-          if [[ ${ALLUXIO_UNDERFS_ADDRESS} == ${scheme}://* ]]; then
-            # if ufs is not local filesystem, don't format
-            exit 0
-          fi
-        done
-
-        shift # remove -s param
-      fi
-    else
-      echo "{Usage} $0 format [-s]"
-      exit 2
-    fi
-  elif [[ $# -gt 1 ]]; then
-    echo "${Usage} $0 format [-s]"
-    exit 2
+function main {
+  LAUNCHER=
+  # If debugging is enabled propagate that through to sub-shells
+  if [[ $- == *x* ]]; then
+    LAUNCHER="bash -x"
   fi
+  BIN=$(cd "$( dirname "$0" )"; pwd)
 
-  ${LAUNCHER} ${BIN}/alluxio-workers.sh ${BIN}/alluxio formatWorker
-
-  echo "Formatting Alluxio Master @ ${ALLUXIO_MASTER_ADDRESS}"
-  CLASS="alluxio.cli.Format"
-  PARAMETER="master"
-;;
-"formatWorker")
-  echo "Formatting Alluxio Worker @ `hostname -f`"
-  CLASS="alluxio.cli.Format"
-  PARAMETER="worker"
-;;
-"fs")
-  CLASS="alluxio.shell.AlluxioShell"
-;;
-"loadufs")
-  CLASS="alluxio.client.UfsUtils"
-;;
-"runClass")
-  CLASS=$1
-  shift
-;;
-"runTest")
-  CLASS="alluxio.cli.RunTests"
-  PARAMETER="alluxio://${ALLUXIO_MASTER_ADDRESS}:19998"
-  ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
-;;
-"runKVTest")
-  CLASS="alluxio.examples.keyvalue.KeyValueStoreOperations"
-  PARAMETER="/default_tests_files/KeyValueStoreOperations"
-  ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
-;;
-"runTests")
-  CLASS="alluxio.cli.RunTests"
-  PARAMETER="alluxio://${ALLUXIO_MASTER_ADDRESS}:19998"
-  ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
-;;
-"runJournalCrashTest")
-  CLASS="alluxio.cli.JournalCrashTest"
-  ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
-;;
-"readJournal")
-  CLASS="alluxio.master.journal.JournalTool"
-;;
-"killAll")
-  killAll $@
-  exit 0
-;;
-"copyDir")
-  copyDir $@
-  exit 0
-;;
-"thriftGen")
-  declare -a thriftSrcPaths=($(find "${BIN}/.." -name "*.thrift" -print0 | xargs -0 -n1 dirname | sort | uniq))
-  for thriftSrcPath in ${thriftSrcPaths[@]}; do
-    rm -rf "${thriftSrcPath}/../main/java/alluxio/thrift"
-    for srcFile in $(ls "${thriftSrcPath}"); do
-      thrift -I "${BIN}/../core/common/src/thrift" --gen java:private-members -out "${thriftSrcPath}/../main/java/." "${thriftSrcPath}/${srcFile}"
-    done
-  done
-  exit 0
-;;
-"protoGen")
-  rm -rf ${BIN}/../core/server/src/main/java/alluxio/proto
-  for src_file in $(find ${BIN}/../core/server/src/proto -type f); do
-    protoc --java_out=${BIN}/../core/server/src/main/java --proto_path=`dirname ${src_file}` ${src_file}
-  done
-  exit 0
-;;
-"clearCache")
-  sync; echo 3 > /proc/sys/vm/drop_caches ;
-  exit 0
-;;
-"version")
-  CLASS="alluxio.cli.Version"
-;;
-"validateConf")
-  CLASS="alluxio.cli.ValidateConf"
-;;
-*)
-  echo "Unsupported command ${COMMAND}"
-  printUsage
-  exit 1
-;;
-esac
-
-while getopts ":D:" opt; do
-  case ${opt} in
-  D)
-    ALLUXIO_SHELL_JAVA_OPTS+=" -D${OPTARG}"
-    ;;
-  \?)
-    echo "Invalid option: -${OPTARG}"
+  if [[ $# == 0 ]]; then
     printUsage
     exit 1
-    ;;
-  esac
-done
-shift $((${OPTIND} - 1))
+  fi
 
-${JAVA} -cp ${CLASSPATH} ${ALLUXIO_USER_JAVA_OPTS} ${ALLUXIO_SHELL_JAVA_OPTS} ${CLASS} ${PARAMETER} $@
+  COMMAND=$1
+  shift
+
+  # bootstrap creates alluxio-env.sh
+  if [[ "${COMMAND}" == "bootstrap-conf" ]]; then
+    bootstrapConf "$@"
+    exit 0
+  fi
+
+  DEFAULT_LIBEXEC_DIR="${BIN}"/../libexec
+  ALLUXIO_LIBEXEC_DIR=${ALLUXIO_LIBEXEC_DIR:-$DEFAULT_LIBEXEC_DIR}
+  . ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
+
+  PARAMETER=""
+  ALLUXIO_SHELL_JAVA_OPTS=""
+
+  case ${COMMAND} in
+  "format")
+    if [[ $# -eq 1 ]]; then
+      if [[ $1 == "-s" ]]; then
+        if [[ -e ${ALLUXIO_UNDERFS_ADDRESS} ]]; then
+          # if ufs is local filesystem and already exists
+          exit 0
+        else
+          declare -a schemes=(hdfs s3 s3n glusterfs swift oss gcs)
+          for scheme in ${schemes[@]}; do
+            if [[ ${ALLUXIO_UNDERFS_ADDRESS} == ${scheme}://* ]]; then
+              # if ufs is not local filesystem, don't format
+              exit 0
+            fi
+          done
+
+          shift # remove -s param
+        fi
+      else
+        echo "{Usage} $0 format [-s]"
+        exit 2
+      fi
+    elif [[ $# -gt 1 ]]; then
+      echo "${Usage} $0 format [-s]"
+      exit 2
+    fi
+
+    ${LAUNCHER} ${BIN}/alluxio-workers.sh ${BIN}/alluxio formatWorker
+
+    echo "Formatting Alluxio Master @ ${ALLUXIO_MASTER_ADDRESS}"
+    CLASS="alluxio.cli.Format"
+    PARAMETER="master"
+  ;;
+  "formatWorker")
+    echo "Formatting Alluxio Worker @ `hostname -f`"
+    CLASS="alluxio.cli.Format"
+    PARAMETER="worker"
+  ;;
+  "fs")
+    CLASS="alluxio.shell.AlluxioShell"
+  ;;
+  "loadufs")
+    CLASS="alluxio.client.UfsUtils"
+  ;;
+  "runClass")
+    CLASS=$1
+    shift
+  ;;
+  "runTest")
+    CLASS="alluxio.cli.RunTests"
+    PARAMETER="alluxio://${ALLUXIO_MASTER_ADDRESS}:19998"
+    ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
+  ;;
+  "runKVTest")
+    CLASS="alluxio.examples.keyvalue.KeyValueStoreOperations"
+    PARAMETER="/default_tests_files/KeyValueStoreOperations"
+    ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
+  ;;
+  "runTests")
+    CLASS="alluxio.cli.RunTests"
+    PARAMETER="alluxio://${ALLUXIO_MASTER_ADDRESS}:19998"
+    ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
+  ;;
+  "runJournalCrashTest")
+    CLASS="alluxio.cli.JournalCrashTest"
+    ALLUXIO_SHELL_JAVA_OPTS+=" -Dalluxio.logger.type=Console"
+  ;;
+  "readJournal")
+    CLASS="alluxio.master.journal.JournalTool"
+  ;;
+  "killAll")
+    killAll $@
+    exit 0
+  ;;
+  "copyDir")
+    copyDir $@
+    exit 0
+  ;;
+  "thriftGen")
+    declare -a thriftSrcPaths=($(find "${BIN}/.." -name "*.thrift" -print0 | xargs -0 -n1 dirname | sort | uniq))
+    for thriftSrcPath in ${thriftSrcPaths[@]}; do
+      rm -rf "${thriftSrcPath}/../main/java/alluxio/thrift"
+      for srcFile in $(ls "${thriftSrcPath}"); do
+        thrift -I "${BIN}/../core/common/src/thrift" --gen java:private-members -out "${thriftSrcPath}/../main/java/." "${thriftSrcPath}/${srcFile}"
+      done
+    done
+    exit 0
+  ;;
+  "protoGen")
+    rm -rf ${BIN}/../core/server/src/main/java/alluxio/proto
+    for src_file in $(find ${BIN}/../core/server/src/proto -type f); do
+      protoc --java_out=${BIN}/../core/server/src/main/java --proto_path=`dirname ${src_file}` ${src_file}
+    done
+    exit 0
+  ;;
+  "clearCache")
+    sync; echo 3 > /proc/sys/vm/drop_caches ;
+    exit 0
+  ;;
+  "version")
+    CLASS="alluxio.cli.Version"
+  ;;
+  "validateConf")
+    CLASS="alluxio.cli.ValidateConf"
+  ;;
+  *)
+    echo "Unsupported command ${COMMAND}"
+    printUsage
+    exit 1
+  ;;
+  esac
+
+  while getopts ":D:" opt; do
+    case ${opt} in
+    D)
+      ALLUXIO_SHELL_JAVA_OPTS+=" -D${OPTARG}"
+      ;;
+    \?)
+      echo "Invalid option: -${OPTARG}"
+      printUsage
+      exit 1
+      ;;
+    esac
+  done
+  shift $((${OPTIND} - 1))
+
+  ${JAVA} -cp ${CLASSPATH} ${ALLUXIO_USER_JAVA_OPTS} ${ALLUXIO_SHELL_JAVA_OPTS} ${CLASS} ${PARAMETER} $@
+}
+
+main "$@"
