Move utility functions to top of script

diff --git a/bin/launch-process b/bin/launch-process
--- a/bin/launch-process
+++ b/bin/launch-process
@@ -34,6 +34,55 @@ unless you know what you are doing.
     -h                Print this help text to stdout
 "
 
+# returns 1 if "$1" contains "$2", 0 otherwise.
+contains() {
+  if [[ "$1" = *"$2"* ]]; then
+    return 1
+  fi
+  return 0
+}
+
+# Sets environment variables by sourcing ${ALLUXIO_HOME}/libexec/alluxio-config.sh
+# or the value of ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
+#
+# The variables that should be set after running this function:
+# - ALLUXIO_JAVA_OPTS
+# - ALLUXIO_MASTER_JAVA_OPTS
+# - ALLUXIO_SECONDARY_MASTER_JAVA_OPTS
+# - ALLUXIO JOB_MASTER_JAVA_OPTS
+# - ALLUXIO_WORKER_JAVA_OPTS
+# - ALLUXIO_JOB_WORKER_JAVA_OPTS
+# - ALLUXIO_PROXY_JAVA_OPTS
+# - ALLUXIO_LOGSERVER_JAVA_OPTS
+
+# If any of these variables are not set after running this function, then the
+# rest of this script may not function properly.
+#
+# Environment Variables:
+#     ALLUXIO_LIBEXEC_DIR: (Optional) Set this value if you want to use a
+#                          libexec directory other than the one located in
+#                          ${ALLUXIO_HOME}.
+get_env() {
+  DEFAULT_LIBEXEC_DIR="${BIN}"/../libexec
+  ALLUXIO_LIBEXEC_DIR=${ALLUXIO_LIBEXEC_DIR:-${DEFAULT_LIBEXEC_DIR}}
+  . ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
+}
+
+# print the help text for this script
+#
+# Arguments:
+#         1: The exit code
+print_help() {
+  if [[ "${1}" -ne "0" ]]; then
+    echo -e "${USAGE}" >&2
+  else
+    echo -e "${USAGE}"
+  fi
+
+  exit ${1}
+}
+
+
 # Launches an Alluxio process
 #
 # Arguments:
@@ -127,54 +176,6 @@ launch_logserver() {
   launch_process "${ALLUXIO_LOGSERVER_JAVA_OPTS}" \
                  "alluxio.logserver.AlluxioLogServer" \
                  "${ALLUXIO_LOGSERVER_LOGS_DIR}"
-}
-
-# returns 1 if "$1" contains "$2", 0 otherwise.
-contains() {
-  if [[ "$1" = *"$2"* ]]; then
-    return 1
-  fi
-  return 0
-}
-
-# Sets environment variables by sourcing ${ALLUXIO_HOME}/libexec/alluxio-config.sh
-# or the value of ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
-#
-# The variables that should be set after running this function:
-# - ALLUXIO_JAVA_OPTS
-# - ALLUXIO_MASTER_JAVA_OPTS
-# - ALLUXIO_SECONDARY_MASTER_JAVA_OPTS
-# - ALLUXIO JOB_MASTER_JAVA_OPTS
-# - ALLUXIO_WORKER_JAVA_OPTS
-# - ALLUXIO_JOB_WORKER_JAVA_OPTS
-# - ALLUXIO_PROXY_JAVA_OPTS
-# - ALLUXIO_LOGSERVER_JAVA_OPTS
-
-# If any of these variables are not set after running this function, then the
-# rest of this script may not function properly.
-#
-# Environment Variables:
-#     ALLUXIO_LIBEXEC_DIR: (Optional) Set this value if you want to use a
-#                          libexec directory other than the one located in
-#                          ${ALLUXIO_HOME}.
-get_env() {
-  DEFAULT_LIBEXEC_DIR="${BIN}"/../libexec
-  ALLUXIO_LIBEXEC_DIR=${ALLUXIO_LIBEXEC_DIR:-${DEFAULT_LIBEXEC_DIR}}
-  . ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
-}
-
-# print the help text for this script
-#
-# Arguments:
-#         1: The exit code
-print_help() {
-  if [[ "${1}" -ne "0" ]]; then
-    echo -e "${USAGE}" >&2
-  else
-    echo -e "${USAGE}"
-  fi
-
-  exit ${1}
 }
 
 # Launch the desired process
