Improve alluxio-fuse shell codestyle

diff --git a/integration/fuse/bin/alluxio-fuse b/integration/fuse/bin/alluxio-fuse
--- a/integration/fuse/bin/alluxio-fuse
+++ b/integration/fuse/bin/alluxio-fuse
@@ -12,8 +12,31 @@
 
 SCRIPT_DIR="$(cd "$(dirname "$(readlink "$0" || echo "$0")")"; pwd)"
 
+readonly USAGE_MSG="Usage:\n\talluxio-fuse [mount|umount|stat]
+
+mount \tmount an Alluxio path to local file system
+umount \tunmount an Alluxio path from local file system
+stat \tshow status of Alluxio mount points"
+
+readonly MOUNT_USAGE="
+Mounts a path in Alluxio namespace (defaults to "/") to mount point on local file system.
+When no argument is given, list the current mount point
+
+Usage:\talluxio-fuse mount [-n] [-o <mount option>] <mount_point> [alluxio_path]
+\talluxio-fuse mount
+
+-o \tmount options for the fuse daemon
+-n \tno-daemon. This launches the process in the foreground and logs to stdout
+-s \tstackFS. This launches StackFS process for testing purpose"
+
+readonly UMOUNT_USAGE="
+Usage:\n\talluxio-fuse umount [-f] [-w <umount wait timeout>] <mount_point>\n\tuse mount stat to show mount points
+
+-f \tif '-f' specified, fuse process will be forcibly killed even if fuse device is busy
+-w \tumount wait timeout in seconds. Timeout to wait for fuse process to exit when '-f' is not set. Default is 120"
+
 get_env() {
-  DEFAULT_LIBEXEC_DIR="${SCRIPT_DIR}"/../../../libexec
+  DEFAULT_LIBEXEC_DIR=${SCRIPT_DIR}/../../../libexec
   ALLUXIO_LIBEXEC_DIR=${ALLUXIO_LIBEXEC_DIR:-${DEFAULT_LIBEXEC_DIR}}
   . ${ALLUXIO_LIBEXEC_DIR}/alluxio-config.sh
 
@@ -22,8 +45,8 @@ get_env() {
 }
 
 check_fuse_jar() {
-  if ! [[ -f ${ALLUXIO_FUSE_JAR} ]]; then
-    echo "Cannot find ${ALLUXIO_FUSE_JAR}. Please compile alluxio with fuse profile and Java 8"
+  if ! [[ -f "${ALLUXIO_FUSE_JAR}" ]]; then
+    err "Cannot find ${ALLUXIO_FUSE_JAR}"
     return 1
   else
     return 0
@@ -34,7 +57,7 @@ mount_fuse() {
   local mount_point=$1
   local alluxio_root=$2
   local full_mount_option=""
-  if [[ ! -z "${mount_option}" ]]; then
+  if [[ -n "${mount_option}" ]]; then
     full_mount_option="big_writes,${mount_option}"
   else
     full_mount_option="big_writes"
@@ -50,7 +73,7 @@ mount_fuse() {
     -m ${mount_point} \
     -r ${alluxio_root}"
   if [[ ${STACK_FS} = true ]]; then
-    stackfs_mount_option=`echo "${full_mount_option}" | sed -E 's/([^,]+)/-o\1/g' | sed -E 's/,/ /g'`
+    stackfs_mount_option="$(echo "${full_mount_option}" | sed -E 's/([^,]+)/-o\1/g' | sed -E 's/,/ /g')"
 
     cmd="${JAVA} -cp ${CLASSPATH} ${JAVA_OPTS} ${ALLUXIO_FUSE_JAVA_OPTS} \
     alluxio.fuse.StackMain \
@@ -66,7 +89,7 @@ mount_fuse() {
   if [[ ${NO_DAEMON} = true ]]; then
     exec ${cmd}
   else
-    (nohup ${cmd} > ${ALLUXIO_LOGS_DIR}/fuse.out 2>&1) &
+    (nohup "${cmd}" > "${ALLUXIO_LOGS_DIR}"/fuse.out 2>&1) &
     # sleep: workaround to let the bg java process exit on errors, if any
     sleep 2s
     if kill -0 $! > /dev/null 2>&1 ; then
@@ -74,8 +97,8 @@ mount_fuse() {
       echo "See ${ALLUXIO_LOGS_DIR}/fuse.log for logging messages"
       return 0
     else
-      echo "Failed to mount Alluxio path \"${alluxio_root}\" to ${mount_point}."
-      echo "See ${ALLUXIO_LOGS_DIR}/fuse.out for more details"
+      err "Failed to mount Alluxio path \"${alluxio_root}\" to ${mount_point}."
+      err "See ${ALLUXIO_LOGS_DIR}/fuse.out for more details"
       return 1
     fi
   fi
@@ -83,38 +106,35 @@ mount_fuse() {
 
 kill_and_umount_fuse() {
   local mount_point=${1%/}
-  local fuse_pid=$(fuse_stat | awk '{print $1,$2}' | grep -w ${mount_point} | awk '{print $1}')
+  local fuse_pid="$(fuse_stat | awk '{print $1,$2}' | grep -w ${mount_point} | awk '{print $1}')"
   if [[ -z ${fuse_pid} ]]; then
     umount_fuse
-    echo "${mount_point} not mounted" >&2
+    err "${mount_point} not mounted"
     return 1
   fi
   if [[ "${FORCE_KILL_OPT}" = true ]] ; then
-    kill -9 ${fuse_pid} 2> /dev/null
+    kill -9 "${fuse_pid}"
     echo "Forcibly killed fuse process ${fuse_pid}"
     umount_fuse
     return $?
   fi
 
-  kill ${fuse_pid}
+  kill "${fuse_pid}"
   echo "Terminating fuse process ${fuse_pid}"
-  if [[ -z "${wait_time}" ]]; then
-    wait_time=120
-  fi  
-  local cnt=${wait_time}
-  while kill -0 ${fuse_pid} > /dev/null 2>&1; do
-    if [[ ${cnt} -gt 1 ]]; then
+  local cnt="${wait_time}"
+  while kill -0 "${fuse_pid}" > /dev/null 2>&1; do
+    if [[ "${cnt}" -gt 1 ]]; then
       # still not dead, wait
       printf '.'
-      cnt=$(expr ${cnt} - 2)
+      (( cnt -= 2 ))
       sleep 2
     else
       printf '\n'
-      echo "Failed to kill fuse process [${fuse_pid}] after "${wait_time}" seconds. " >&2
-      echo "Fuse process may still in the exiting process if \"alluxio.fuse.umount.timeout\" is bigger than ${wait_time} seconds. " >&2
-      echo "Fuse process may not be able to exit when the fuse device is busy (have ongoing reading/writing operations). " >&2
-      echo "See ${ALLUXIO_LOGS_DIR}/fuse.log for more details. " >&2
-      echo "Run \"alluxio-fuse umount -f <mount_point>\" if needed to forcibly kill the alluxio fuse process and fuse mount point. " >&2
+      err "Failed to kill fuse process [${fuse_pid}] after ${wait_time} seconds. 
+Fuse process may still in the exiting process if \"alluxio.fuse.umount.timeout\" is bigger than ${wait_time} seconds. 
+Fuse process may not be able to exit when the fuse device is busy (have ongoing reading/writing operations). 
+See ${ALLUXIO_LOGS_DIR}/fuse.log for more details.
+Run \"alluxio-fuse umount -f <mount_point>\" if needed to forcibly kill the alluxio fuse process and fuse mount point. "
       return 1
     fi
   done
@@ -125,27 +145,25 @@ kill_and_umount_fuse() {
 
 umount_fuse() {
   # TODO(lu) check if fuse is mounted before umounting
-  umount ${mount_point} 2> /dev/null
   success_msg="Successfully unmount fuse at ${mount_point} (PID: ${fuse_pid})"
-  if [[ $? -eq 0 ]]; then
+  if umount "${mount_point}"; then
     echo "${success_msg}"
     return 0
   fi
-  fusermount -u -z ${mount_point} 2> /dev/null
-  if [[ $? -eq 0 ]]; then
+  if fusermount -u -z "${mount_point}"; then
     echo "${success_msg}"
     return 0
   fi
-  umount -f ${mount_point} 2> /dev/null
-  if [[ $? -eq 0 ]]; then
+  if umount -f "${mount_point}"; then
     echo "${success_msg}"
     return 0
   fi
-  echo "Failed to umount fuse mount point ${mount_point}"
+  err "Failed to umount fuse mount point ${mount_point}"
   return 1
 }
 
 fuse_stat() {
+  # TODO(lu) using pgrep instead of ps and grep
   local fuse_info=$(ps aux | grep [A]lluxioFuse)
   if [[ -n ${fuse_info} ]]; then
     echo -e "pid\tmount_point\talluxio_path"
@@ -154,123 +172,124 @@ fuse_stat() {
   fi
   fuse_info=$(ps ax -o pid,args | grep [A]lluxioWorker | grep alluxio\.worker\.fuse\.enabled=true)
   if [[ -n ${fuse_info} ]]; then
-    fuse_worker_pid="$(echo ${fuse_info} | awk '{print $1}')"
-    fuse_mount_point="$(echo ${fuse_info} | grep -Po '(?<=alluxio\.worker\.fuse\.mount\.point=)\S+(?=\s)')"
-    fuse_alluxio_path="$(echo ${fuse_info} | grep -Po '(?<=alluxio\.worker\.fuse\.mount\.alluxio\.path=)\S+(?=\s)')"
+    fuse_worker_pid="$(echo "${fuse_info}" | awk '{print $1}')"
+    fuse_mount_point="$(echo "${fuse_info}" | grep -Po '(?<=alluxio\.worker\.fuse\.mount\.point=)\S+(?=\s)')"
+    fuse_alluxio_path="$(echo "${fuse_info}" | grep -Po '(?<=alluxio\.worker\.fuse\.mount\.alluxio\.path=)\S+(?=\s)')"
     echo -e "pid\tmount_point\talluxio_path"
     echo -e "${fuse_worker_pid}\t${fuse_mount_point}\t${fuse_alluxio_path}"
     return 0
   fi
-  fuse_info=$(ps aux | grep [S]tackMain)
-  if [[ -n ${fuse_info} ]]; then
+  fuse_info="$(ps aux | grep [S]tackMain)"
+  if [[ -n "${fuse_info}" ]]; then
     echo -e "pid\tmount_point\tsource_path"
     echo -e "$(ps ax -o pid,args | grep [S]tackMain | awk -F' ' '{print $1 "\t" $(NF-2) "\t" $(NF-1)}')"
     return 0
   fi
-  echo "No mount point found. AlluxioFuse process is not running."
-  echo -e "${MOUNT_USAGE}"
+  err "No mount point found. AlluxioFuse process is not running."
+  echo -e "${MOUNT_USAGE}" >&2
   return 1
 }
 
-USAGE_MSG="Usage:\n\talluxio-fuse [mount|umount|stat]
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+}
 
-mount \tmount an Alluxio path to local file system
-umount \tunmount an Alluxio path from local file system
-stat \tshow status of Alluxio mount points"
-
-MOUNT_USAGE="
-Mounts a path in Alluxio namespace (defaults to "/") to mount point on local file system.
-When no argument is given, list the current mount point
-
-Usage:\talluxio-fuse mount [-n] [-o <mount option>] <mount_point> [alluxio_path]
-\talluxio-fuse mount
-
--o \tmount options for the fuse daemon
--n \tno-daemon. This launches the process in the foreground and logs to stdout
--s \tstackFS. This launches StackFS process for testing purpose"
-
-UMOUNT_USAGE="
-Usage:\n\talluxio-fuse umount [-f] [-w <umount wait timeout>] <mount_point>\n\tuse mount stat to show mount points
-
--f \tif '-f' specified, fuse process will be forcibly killed even if fuse device is busy
--w \tumount wait timeout in seconds. Timeout to wait for fuse process to exit when '-f' is not set. Default is 120"
-
-if [[ $# -lt 1 ]]; then
-  echo -e "${USAGE_MSG}" >&2
-  exit 1
-fi
-
-get_env
-check_fuse_jar
-if [[ $? -ne 0 ]]; then
-  exit 1
-fi
-
-case $1 in
-  mount)
-    shift
-    while getopts "o:ns" option; do
-      case "${option}" in
-        o)
-          mount_option=${OPTARG}
-          ;;
-        n)
-          NO_DAEMON=true
-          ;;
-        s)
-          STACK_FS=true
-          ;;
-        *)
-          echo -e "${MOUNT_USAGE}" >&2
-          exit 1
-          ;;
-      esac
-    done
-    shift $((${OPTIND} - 1))
-    if [[ $# -eq 0 ]]; then
-      fuse_stat
-      exit $?
-    fi
-    if [[ $# -eq 1 ]]; then
-      mount_fuse $1 /
-      exit $?
-    fi
-    if [[ $# -eq 2 ]]; then
-      mount_fuse $1 $2
-      exit $?
-    fi
-    echo -e "${MOUNT_USAGE}" >&2
+main() {
+  if [[ $# -lt 1 ]]; then
+    err "More than one command passed in"
+    echo -e "${USAGE_MSG}" >&2
     exit 1
-    ;;
-  umount|unmount)
-    shift
-      while getopts "w:f" option; do
+  fi
+  
+  get_env
+  if check_fuse_jar; then
+    exit 1
+  fi
+  
+  NO_DAEMON=false
+  STACK_FS=false
+  FORCE_KILL_OPT=false
+  mount_point=''
+  wait_time=120
+  command=$1
+  case "${command}" in
+    mount)
+      shift
+      while getopts 'o:ns' option; do
+        case "${option}" in
+          o)
+            mount_option="${OPTARG}"
+            ;;
+          n)
+            NO_DAEMON=true
+            ;;
+          s)
+            STACK_FS=true
+            ;;
+          *)
+            err "Invalid mount option ${option}"
+            echo -e "${MOUNT_USAGE}" >&2
+            exit 1
+            ;;
+        esac
+      done
+      readonly NO_DAEMON
+      readonly STACK_FS
+
+      shift $(( OPTIND - 1 ))
+      if [[ $# -eq 0 ]]; then
+        fuse_stat
+        exit $?
+      fi
+      if [[ $# -eq 1 ]]; then
+        mount_fuse "$1" /
+        exit $?
+      fi
+      if [[ $# -eq 2 ]]; then
+        mount_fuse "$1" "$2"
+        exit $?
+      fi
+      err "Invalid mount option ${option}"
+      echo -e "${MOUNT_USAGE}" >&2
+      exit 1
+      ;;
+    umount|unmount)
+      shift
+      while getopts 'w:f' option; do
         case "${option}" in
           w)
-            wait_time=${OPTARG}
+            wait_time="${OPTARG}"
             ;;
           f)
             FORCE_KILL_OPT=true
             ;;
           *)
+          err "Invalid umount option ${option}"
           echo -e "${UMOUNT_USAGE}" >&2
           exit 1
           ;;
         esac
       done
-    shift $((${OPTIND} - 1))
-    if [[ $# -eq 1 ]]; then
-      kill_and_umount_fuse $1
-      exit $?
-    fi
-    echo -e "${UMOUNT_USAGE}" >&2
-    exit 1
-    ;;
-  stat)
-    fuse_stat
-    ;;
-  *)
-    echo -e "${USAGE_MSG}" >&2
-    exit 1
-    ;;
-esac
+      readonly FORCE_KILL_OPT
+
+      shift $(( OPTIND - 1 ))
+      if [[ $# -eq 1 ]]; then
+        kill_and_umount_fuse "$1"
+        exit $?
+      fi
+      err "Umount expects exactly one fuse_mount_point parameter"
+      echo -e "${UMOUNT_USAGE}" >&2
+      exit 1
+      ;;
+    stat)
+      fuse_stat
+      ;;
+    *)
+      err "Invalid command ${command}"
+      echo -e "${USAGE_MSG}" >&2
+      exit 1
+      ;;
+  esac
+}
+
+main "$@"
